export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const ADD_TO_CART = "ADD_TO_CART";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const STORE_USER_INFO = "STORE_USER_INFO";
export const STORE_RECIPIENT_INFO = "STORE_RECIPIENT_INFO";
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_RECIPIENT="CLEAR_RECIPIENT"